[package]
name = "discord_interactions"
version = "0.1.0"
authors = ["Hugo Woesthuis <hugow2011@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.13.0"
env_logger = "0"
serde_repr = "0.1"
rustls = "0.18"
actix-web = {version = "3", features=["rustls"]}
actix-files = "0.3"
actix-rt = "2"
ed25519-dalek = "1"
hex = "0.4"
async-trait = "0.1"
serde_json = "1"
chrono = "0.4"
discord_interactions_macros = {path="attributes"}
log="0"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_with]
version = "1.8.0"
features = [ "macros", "chrono", "json" ]