[package]
name = "rusty_interaction"
version = "0.1.0"
authors = ["Hugo Woesthuis <hugow2011@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
# For types
serde_repr = "0.1"
serde_json = "1"
chrono = "0.4"

# For security
ed25519-dalek = {version = "1", optional = true}
hex = {version = "0.4", optional = true}

# For handler
env_logger = {version = "0", optional = true}

rustls = {version = "0.18", optional = true} 
actix-web = {version = "3", features=["rustls"], optional = true}
actix-files = {version = "0.3", optional = true}
actix-rt = {version = "2", optional = true}

async-trait = {version = "0.1", optional = true}

discord_interactions_macros = {path="attributes", optional=true}
log = {version = "0", optional = true}

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_with]
version = "1.8.0"
features = [ "macros", "chrono", "json" ]


[features]
default = ["types", "security"]
security = ["ed25519-dalek", "hex", "types"]
types = []
handler = ["types", "security", "actix-web", "actix-files", "actix-rt", "rustls", "async-trait", "discord_interactions_macros", "log"]


