[package]
name = "attributes"
version = "0.0.1"
authors = ["Hugo Woesthuis <hugow2011@outlook.com>"]
edition = "2018"
description = "Procedural macros for command creation with rusty-interaction"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0.71", features=["full"]}
quote = {version = "1.0.9"}