name: Rust Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: examples
      run: cargo build

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: 'bash -c "find examples/ -not \( -path \"examples/target\" -prune \) -name \"*.rs\" | xargs rustfmt --check"'
