name: RustCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests on handler
      run: cargo test --verbose --features handler
    - name: Run tests on extended-handler
      run: cargo test --verbose --features extended-handler
